name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # clone the source code containing the package version generation script
      - name: Checkout source code
        uses: actions/checkout@main
        with:
          submodules: true

      # make sure python is set up properly
      - name: Install Python (with dependencies)
        uses: actions/setup-python@main
        with:
          python-version: '3.12'

      - name: Install ffmpeg for video recording
        run: sudo apt-get install ffmpeg

      - name: Install pip dependencies
        run: |
          python -m pip install pip --upgrade
          pip install uv
          uv --version
          uv venv --python 3.12
          source .venv/bin/activate
          # uv pip install wheel==0.37.1 setuptools==59.6.0
          uv pip install -r ./fast-pysf/requirements.txt
          uv pip install -r ./requirements.txt

      - name: Register modules under test
        run: |
          source .venv/bin/activate
          cd fast-pysf && uv pip install . && cd ..
          uv pip install .

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest tests

      - name: Run pylint
        run: |
          source .venv/bin/activate
          python -m pylint robot_sf

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
      - name: Ruff Check
        run: ruff check
      - name: Ruff Format
        run: ruff format

