name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.11"

      - name: Set up Python
        run: uv python install 3.12

      - name: Update package list
        run: sudo apt-get update

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.11"
          
      - name: Set up Python  
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Ruff linting
        run: uv run ruff check .

      - name: Run Ruff formatting
        run: uv run ruff format --check .
